/// screenshot_test_generator.dart
///
/// Run with: dart run scripts/screenshot_test_generator.dart
///
/// Reads lib/routes.dart, extracts all GoRouter routes,
/// and generates integration_test/screenshot_test.dart

import 'dart:io';

void main() {
  final routesFile = File('lib/routes.dart');

  if (!routesFile.existsSync()) {
    print('❌ lib/routes.dart not found. Create your routes first.');
    exit(1);
  }

  final content = routesFile.readAsStringSync();

  // Extract route paths from GoRoute definitions
  // Matches: path: '/home', path: '/settings', etc.
  final pathRegex = RegExp(r"path:\s*'([^']+)'");
  final matches = pathRegex.allMatches(content);

  final routes = <Map<String, String>>[];
  var index = 1;

  for (final match in matches) {
    final path = match.group(1)!;
    // Skip parameter routes like /detail/:id for now
    if (path.contains(':')) continue;

    final name = path
        .replaceAll('/', '_')
        .replaceAll(RegExp(r'^_'), '')
        .replaceAll(RegExp(r'_$'), '');

    final safeName = name.isEmpty ? 'home' : name;
    final paddedIndex = index.toString().padLeft(2, '0');

    routes.add({
      'path': path,
      'name': safeName,
      'screenshot': '${paddedIndex}_$safeName',
    });
    index++;
  }

  if (routes.isEmpty) {
    print('⚠️  No routes found in lib/routes.dart');
    print('   Make sure routes use: path: \'/your_path\'');
    exit(1);
  }

  print('📋 Found ${routes.length} routes:');
  for (final r in routes) {
    print('   ${r['path']} → ${r['screenshot']}.png');
  }

  // Generate the test file
  final pubspec = File('pubspec.yaml');
  final pubContent = pubspec.readAsStringSync();
  final nameMatch = RegExp(r'^name:\s*(\S+)', multiLine: true).firstMatch(pubContent);
  final appName = nameMatch?.group(1) ?? 'my_app';

  final buffer = StringBuffer();

  buffer.writeln("// AUTO-GENERATED — do not edit manually");
  buffer.writeln("// Generated by: dart run scripts/screenshot_test_generator.dart");
  buffer.writeln("// Date: ${DateTime.now().toIso8601String()}");
  buffer.writeln();
  buffer.writeln("import 'package:integration_test/integration_test.dart';");
  buffer.writeln("import 'package:flutter_test/flutter_test.dart';");
  buffer.writeln("import 'package:flutter/material.dart';");
  buffer.writeln("import 'package:$appName/main.dart' as app;");
  buffer.writeln();
  buffer.writeln("void main() {");
  buffer.writeln("  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();");
  buffer.writeln();
  buffer.writeln("  testWidgets('Capture all app screens', (tester) async {");
  buffer.writeln("    app.main();");
  buffer.writeln("    await tester.pumpAndSettle();");
  buffer.writeln();
  buffer.writeln("    // Wait for app to fully load");
  buffer.writeln("    await Future.delayed(const Duration(seconds: 2));");
  buffer.writeln("    await tester.pumpAndSettle();");
  buffer.writeln();

  for (final route in routes) {
    buffer.writeln("    // --- Screen: ${route['name']} (${route['path']}) ---");

    if (route['path'] == '/') {
      // Home screen — already loaded
      buffer.writeln("    await binding.convertFlutterSurfaceToImage();");
      buffer.writeln("    await tester.pumpAndSettle();");
      buffer.writeln("    await binding.takeScreenshot('${route['screenshot']}');");
    } else {
      // Navigate to route
      buffer.writeln("    // Navigate to ${route['path']}");
      buffer.writeln("    final nav${route['name']} = find.byType(Navigator).first;");
      buffer.writeln("    // TODO: Add navigation logic for ${route['path']}");
      buffer.writeln("    // Example: await tester.tap(find.text('${route['name']}'));");
      buffer.writeln("    await tester.pumpAndSettle();");
      buffer.writeln("    await Future.delayed(const Duration(milliseconds: 500));");
      buffer.writeln("    await binding.convertFlutterSurfaceToImage();");
      buffer.writeln("    await tester.pumpAndSettle();");
      buffer.writeln("    await binding.takeScreenshot('${route['screenshot']}');");
    }
    buffer.writeln();
  }

  buffer.writeln("    debugPrint('✅ All ${routes.length} screenshots captured!');");
  buffer.writeln("  });");
  buffer.writeln("}");

  // Write the test file
  final testDir = Directory('integration_test');
  if (!testDir.existsSync()) {
    testDir.createSync();
  }

  final testFile = File('integration_test/screenshot_test.dart');
  testFile.writeAsStringSync(buffer.toString());

  print('\n✅ Generated: integration_test/screenshot_test.dart');
  print('   ⚠️  Review the file and add navigation logic for each route.');
  print('   Run: flutter test integration_test/screenshot_test.dart');
}
